<?php

namespace VaultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BillingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillingRepository extends EntityRepository
{
    function get_billing_with_period($timeperiod, $getutilitytype, $getcouncil, $getsite)
    {
        $start = $end = "";
        $period = '';
        $groupby = 'period';
        $orderby = '';

        if ($timeperiod == "2") {
            $last_year_month = date('Y-m', strtotime('last month'));
            $start = $last_year_month . '-01';
            $end = $start;
            $period = "DATE_FORMAT(period,'%M %Y') as period";
        } elseif ($timeperiod > 12) {
            $interval = (($timeperiod / 12) - 1);
            $start_last_years = date('Y', strtotime("-" . $interval . " year"));
            $end_last_years = $start_last_years + 1;

            $start = $start_last_years . '-01-01';
            $end = date('Y-m-d');

            $period = "DATE_FORMAT(period,'%Y') as period";
            $groupby = "DATE_FORMAT(period,'%Y')";
            $orderby = "ORDER BY DATE_FORMAT(period,'%Y') DESC";
        } else {
            $interval = $timeperiod;
            $end = date('Y-m-d');
            $start = date('Y-m-d', strtotime("-" . $interval . " month"));

            $period = "DATE_FORMAT(period,'%M %Y') as period";
            $groupby = "DATE_FORMAT(period,'%M')";
            $orderby = "ORDER BY DATE_FORMAT(period,'%Y %m') DESC";
        }

        $subquery = '';
        $subquery_where = '';
        $sites_list = '';
        $counter = 1;

        if ($getcouncil) {
            $repository = $this->getEntityManager()->getRepository('VaultBundle:Site');
            $sites = $repository->get_all_sites($getcouncil);

            if ($sites) {
                foreach ($sites as $site) {
                    if ($counter > 1) {
                        $sites_list .= ',';
                    }
                    $sites_list .= $site['id'];
                    $counter++;
                }
            }
        }

        if ($getsite || $getutilitytype || $getcouncil) {
            if ($getsite && $getutilitytype) {
                $subquery_where .= "meter.site_id = $getsite AND meter.meter_type = $getutilitytype";
            } elseif ($getutilitytype && $getcouncil) {
                $subquery_where .= "meter.meter_type = $getutilitytype AND meter.site_id IN($sites_list)";
            } elseif ($getutilitytype) {
                $subquery_where .= "meter.meter_type = $getutilitytype";
            } elseif ($getsite) {
                $subquery_where .= "meter.site_id = $getsite";
            } elseif ($getcouncil && $sites_list) {
                $subquery_where .= "meter.site_id IN($sites_list)";
            }
        }

        if ($subquery_where) {
            $subquery .= "SELECT meter.id FROM meter Where $subquery_where";
        }

        if ($subquery) {
            $SQL_QUERY = "SELECT $period,SUM(amount) AS Total
                          FROM billing
                          WHERE meter_id IN ($subquery)
                          AND period BETWEEN '$start' AND '$end'
                          GROUP BY $groupby
                          $orderby";
        } else {
            $SQL_QUERY = "SELECT $period,SUM(amount) AS Total
                          FROM billing
                          WHERE period BETWEEN '$start' AND '$end'
                          GROUP BY $groupby
                          $orderby";
        }

        //echo "sql query is: ".$SQL_QUERY;
        return $this->getEntityManager()->getConnection()->executeQuery($SQL_QUERY)->fetchAll();
    }
}