<?php

namespace VaultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BillingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillingRepository extends EntityRepository
{
}
