<?php

namespace VaultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CouncilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouncilRepository extends EntityRepository
{
}
