<?php

namespace VaultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LookupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LookupRepository extends EntityRepository {

    public function getLookupByType($id) {

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('l')
                ->select('l.code, l.id')
                ->from('VaultBundle:Lookup', 'l')
                ->join('l.baseLookupId', 'b')
                ->where("b.parentId = :param  ")
                ->setParameter('param', $id);
        return $query->getQuery()->getResult();
    }

}
