<?php

namespace VaultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{
    function get_all_sites($councilid){

        $SQL_QUERY = "SELECT id,name FROM site WHERE council_id= $councilid";

        return $this->getEntityManager()->getConnection()->executeQuery($SQL_QUERY)->fetchAll();
    }
}
