<?php

use Symfony\Component\Routing\RequestContext;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use Psr\Log\LoggerInterface;

/**
 * appDevDebugProjectContainerUrlGenerator
 *
 * This class has been auto-generated
 * by the Symfony Routing Component.
 */
class appDevDebugProjectContainerUrlGenerator extends Symfony\Component\Routing\Generator\UrlGenerator
{
    private static $declaredRoutes;

    /**
     * Constructor.
     */
    public function __construct(RequestContext $context, LoggerInterface $logger = null)
    {
        $this->context = $context;
        $this->logger = $logger;
        if (null === self::$declaredRoutes) {
            self::$declaredRoutes = array(
        '_wdt' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:toolbarAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/_wdt',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_home' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:homeAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_search' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:searchAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/search',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_search_bar' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:searchBarAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/search_bar',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_purge' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:purgeAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/purge',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_info' => array (  0 =>   array (    0 => 'about',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:infoAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'about',    ),    1 =>     array (      0 => 'text',      1 => '/_profiler/info',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_phpinfo' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:phpinfoAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/phpinfo',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_search_results' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:searchResultsAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/search/results',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:panelAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_router' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.router:panelAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/router',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_exception' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.exception:showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/exception',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_exception_css' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.exception:cssAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/exception.css',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_twig_error_test' => array (  0 =>   array (    0 => 'code',    1 => '_format',  ),  1 =>   array (    '_controller' => 'twig.controller.preview_error:previewErrorPageAction',    '_format' => 'html',  ),  2 =>   array (    'code' => '\\d+',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '.',      2 => '[^/]++',      3 => '_format',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'code',    ),    2 =>     array (      0 => 'text',      1 => '/_error',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'soft_delete' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\AdminController::softDeleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/softdelete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'contract_dropdown' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\AdminController::contractAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/contract',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'vault_default_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\DefaultController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'vault_default_createmeter' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\DefaultController::createmeterAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/baselookup',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_security_login' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\SecurityFOSUser1Controller::loginAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/login',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_security_check' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\SecurityFOSUser1Controller::checkAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/login_check',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_security_logout' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\SecurityFOSUser1Controller::logoutAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/logout',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_security_login' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\SecurityFOSUser1Controller::loginAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/login',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_security_check' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\SecurityFOSUser1Controller::checkAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/login_check',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_security_logout' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\SecurityFOSUser1Controller::logoutAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/logout',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_resetting_request' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ResettingFOSUser1Controller::requestAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/resetting/request',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_resetting_send_email' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ResettingFOSUser1Controller::sendEmailAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/resetting/send-email',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_resetting_check_email' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ResettingFOSUser1Controller::checkEmailAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/resetting/check-email',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_resetting_reset' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ResettingFOSUser1Controller::resetAction',  ),  2 =>   array (    '_method' => 'GET|POST',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/resetting/reset',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_resetting_request' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ResettingFOSUser1Controller::requestAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/resetting/request',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_resetting_send_email' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ResettingFOSUser1Controller::sendEmailAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/resetting/send-email',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_resetting_check_email' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ResettingFOSUser1Controller::checkEmailAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/resetting/check-email',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_resetting_reset' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ResettingFOSUser1Controller::resetAction',  ),  2 =>   array (    '_method' => 'GET|POST',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/resetting/reset',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_profile_show' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ProfileFOSUser1Controller::showAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/profile/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_profile_edit_authentication' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ProfileFOSUser1Controller::editAuthenticationAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/profile/edit-authentication',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_profile_edit' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ProfileFOSUser1Controller::editProfileAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/profile/edit-profile',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_profile_show' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ProfileFOSUser1Controller::showAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/profile/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_profile_edit_authentication' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ProfileFOSUser1Controller::editAuthenticationAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/profile/edit-authentication',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_profile_edit' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ProfileFOSUser1Controller::editProfileAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/profile/edit-profile',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_registration_register' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\RegistrationFOSUser1Controller::registerAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/register/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_registration_check_email' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\RegistrationFOSUser1Controller::checkEmailAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/register/check-email',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_registration_confirm' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\RegistrationFOSUser1Controller::confirmAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/register/confirm',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_registration_confirmed' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\RegistrationFOSUser1Controller::confirmedAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/register/confirmed',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_registration_register' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\RegistrationFOSUser1Controller::registerAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/register/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_registration_check_email' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\RegistrationFOSUser1Controller::checkEmailAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/register/check-email',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_registration_confirm' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\RegistrationFOSUser1Controller::confirmAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/register/confirm',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_registration_confirmed' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\RegistrationFOSUser1Controller::confirmedAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/register/confirmed',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_change_password' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ChangePasswordFOSUser1Controller::changePasswordAction',  ),  2 =>   array (    '_method' => 'GET|POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/profile/change-password',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_change_password' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\ChangePasswordFOSUser1Controller::changePasswordAction',  ),  2 =>   array (    '_method' => 'GET|POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/profile/change-password',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_admin_security_login' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\AdminSecurityController::loginAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/login',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_admin_security_check' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\AdminSecurityController::checkAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/login_check',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_admin_security_logout' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\AdminSecurityController::logoutAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/logout',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_admin_resetting_request' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\AdminResettingController::requestAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/resetting/request',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_admin_resetting_send_email' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\AdminResettingController::sendEmailAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/resetting/send-email',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_admin_resetting_check_email' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\AdminResettingController::checkEmailAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/resetting/check-email',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_user_admin_resetting_reset' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'Sonata\\UserBundle\\Controller\\AdminResettingController::resetAction',  ),  2 =>   array (    '_method' => 'GET|POST',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/admin/resetting/reset',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_admin_redirect' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction',    'route' => 'sonata_admin_dashboard',    'permanent' => 'true',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_admin_dashboard' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CoreController::dashboardAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/dashboard',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_admin_retrieve_form_element' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'sonata.admin.controller.admin:retrieveFormFieldElementAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/core/get-form-field-element',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_admin_append_form_element' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'sonata.admin.controller.admin:appendFormFieldElementAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/core/append-form-field-element',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_admin_short_object_information' => array (  0 =>   array (    0 => '_format',  ),  1 =>   array (    '_controller' => 'sonata.admin.controller.admin:getShortObjectDescriptionAction',    '_format' => 'html',  ),  2 =>   array (    '_format' => 'html|json',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '.',      2 => 'html|json',      3 => '_format',    ),    1 =>     array (      0 => 'text',      1 => '/admin/core/get-short-object-description',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_admin_set_object_field_value' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'sonata.admin.controller.admin:setObjectFieldValueAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/core/set-object-field-value',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_admin_search' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CoreController::searchAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/search',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'sonata_admin_retrieve_autocomplete_items' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'sonata.admin.controller.admin:retrieveAutocompleteItemsAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/core/get-autocomplete-items',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_baselookup_list' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::listAction',    '_sonata_admin' => 'vault.admin.base_lookup',    '_sonata_name' => 'admin_vault_baselookup_list',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/baselookup/list',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_baselookup_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::createAction',    '_sonata_admin' => 'vault.admin.base_lookup',    '_sonata_name' => 'admin_vault_baselookup_create',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/baselookup/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_baselookup_batch' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::batchAction',    '_sonata_admin' => 'vault.admin.base_lookup',    '_sonata_name' => 'admin_vault_baselookup_batch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/baselookup/batch',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_baselookup_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::editAction',    '_sonata_admin' => 'vault.admin.base_lookup',    '_sonata_name' => 'admin_vault_baselookup_edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/baselookup',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_baselookup_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::showAction',    '_sonata_admin' => 'vault.admin.base_lookup',    '_sonata_name' => 'admin_vault_baselookup_show',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/baselookup',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_baselookup_export' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::exportAction',    '_sonata_admin' => 'vault.admin.base_lookup',    '_sonata_name' => 'admin_vault_baselookup_export',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/baselookup/export',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_baselookup_softDelete' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::softDeleteAction',    '_sonata_admin' => 'vault.admin.base_lookup',    '_sonata_name' => 'admin_vault_baselookup_softDelete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/baselookup/softDelete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_lookup_list' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::listAction',    '_sonata_admin' => 'vault.admin.lookup',    '_sonata_name' => 'admin_vault_lookup_list',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/lookup/list',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_lookup_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::createAction',    '_sonata_admin' => 'vault.admin.lookup',    '_sonata_name' => 'admin_vault_lookup_create',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/lookup/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_lookup_batch' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::batchAction',    '_sonata_admin' => 'vault.admin.lookup',    '_sonata_name' => 'admin_vault_lookup_batch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/lookup/batch',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_lookup_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::editAction',    '_sonata_admin' => 'vault.admin.lookup',    '_sonata_name' => 'admin_vault_lookup_edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/lookup',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_lookup_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::showAction',    '_sonata_admin' => 'vault.admin.lookup',    '_sonata_name' => 'admin_vault_lookup_show',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/lookup',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_lookup_export' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::exportAction',    '_sonata_admin' => 'vault.admin.lookup',    '_sonata_name' => 'admin_vault_lookup_export',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/lookup/export',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_lookup_softDelete' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::softDeleteAction',    '_sonata_admin' => 'vault.admin.lookup',    '_sonata_name' => 'admin_vault_lookup_softDelete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/lookup/softDelete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_profile_list' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::listAction',    '_sonata_admin' => 'vault.admin.profile',    '_sonata_name' => 'admin_vault_profile_list',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/profile/list',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_profile_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::createAction',    '_sonata_admin' => 'vault.admin.profile',    '_sonata_name' => 'admin_vault_profile_create',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/profile/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_profile_batch' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::batchAction',    '_sonata_admin' => 'vault.admin.profile',    '_sonata_name' => 'admin_vault_profile_batch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/profile/batch',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_profile_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::editAction',    '_sonata_admin' => 'vault.admin.profile',    '_sonata_name' => 'admin_vault_profile_edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/profile',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_profile_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::showAction',    '_sonata_admin' => 'vault.admin.profile',    '_sonata_name' => 'admin_vault_profile_show',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/profile',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_profile_export' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::exportAction',    '_sonata_admin' => 'vault.admin.profile',    '_sonata_name' => 'admin_vault_profile_export',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/profile/export',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_profile_softDelete' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::softDeleteAction',    '_sonata_admin' => 'vault.admin.profile',    '_sonata_name' => 'admin_vault_profile_softDelete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/profile/softDelete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_council_list' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::listAction',    '_sonata_admin' => 'vault.admin.council',    '_sonata_name' => 'admin_vault_council_list',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/council/list',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_council_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::createAction',    '_sonata_admin' => 'vault.admin.council',    '_sonata_name' => 'admin_vault_council_create',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/council/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_council_batch' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::batchAction',    '_sonata_admin' => 'vault.admin.council',    '_sonata_name' => 'admin_vault_council_batch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/council/batch',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_council_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::editAction',    '_sonata_admin' => 'vault.admin.council',    '_sonata_name' => 'admin_vault_council_edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/council',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_council_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::showAction',    '_sonata_admin' => 'vault.admin.council',    '_sonata_name' => 'admin_vault_council_show',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/council',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_council_export' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::exportAction',    '_sonata_admin' => 'vault.admin.council',    '_sonata_name' => 'admin_vault_council_export',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/council/export',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_council_softDelete' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::softDeleteAction',    '_sonata_admin' => 'vault.admin.council',    '_sonata_name' => 'admin_vault_council_softDelete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/council/softDelete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_site_list' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::listAction',    '_sonata_admin' => 'vault.admin.site',    '_sonata_name' => 'admin_vault_site_list',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/site/list',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_site_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::createAction',    '_sonata_admin' => 'vault.admin.site',    '_sonata_name' => 'admin_vault_site_create',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/site/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_site_batch' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::batchAction',    '_sonata_admin' => 'vault.admin.site',    '_sonata_name' => 'admin_vault_site_batch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/site/batch',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_site_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::editAction',    '_sonata_admin' => 'vault.admin.site',    '_sonata_name' => 'admin_vault_site_edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/site',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_site_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::showAction',    '_sonata_admin' => 'vault.admin.site',    '_sonata_name' => 'admin_vault_site_show',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/site',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_site_export' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::exportAction',    '_sonata_admin' => 'vault.admin.site',    '_sonata_name' => 'admin_vault_site_export',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/site/export',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_site_softDelete' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::softDeleteAction',    '_sonata_admin' => 'vault.admin.site',    '_sonata_name' => 'admin_vault_site_softDelete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/site/softDelete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_contract_list' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::listAction',    '_sonata_admin' => 'vault.admin.contract',    '_sonata_name' => 'admin_vault_contract_list',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/contract/list',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_contract_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::createAction',    '_sonata_admin' => 'vault.admin.contract',    '_sonata_name' => 'admin_vault_contract_create',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/contract/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_contract_batch' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::batchAction',    '_sonata_admin' => 'vault.admin.contract',    '_sonata_name' => 'admin_vault_contract_batch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/contract/batch',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_contract_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::editAction',    '_sonata_admin' => 'vault.admin.contract',    '_sonata_name' => 'admin_vault_contract_edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/contract',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_contract_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::showAction',    '_sonata_admin' => 'vault.admin.contract',    '_sonata_name' => 'admin_vault_contract_show',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/contract',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_contract_export' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::exportAction',    '_sonata_admin' => 'vault.admin.contract',    '_sonata_name' => 'admin_vault_contract_export',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/contract/export',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_contract_softDelete' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::softDeleteAction',    '_sonata_admin' => 'vault.admin.contract',    '_sonata_name' => 'admin_vault_contract_softDelete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/contract/softDelete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_billing_list' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::listAction',    '_sonata_admin' => 'vault.admin.billing',    '_sonata_name' => 'admin_vault_billing_list',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/billing/list',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_billing_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::createAction',    '_sonata_admin' => 'vault.admin.billing',    '_sonata_name' => 'admin_vault_billing_create',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/billing/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_billing_batch' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::batchAction',    '_sonata_admin' => 'vault.admin.billing',    '_sonata_name' => 'admin_vault_billing_batch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/billing/batch',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_billing_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::editAction',    '_sonata_admin' => 'vault.admin.billing',    '_sonata_name' => 'admin_vault_billing_edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/billing',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_billing_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::showAction',    '_sonata_admin' => 'vault.admin.billing',    '_sonata_name' => 'admin_vault_billing_show',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/billing',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_billing_export' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::exportAction',    '_sonata_admin' => 'vault.admin.billing',    '_sonata_name' => 'admin_vault_billing_export',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/billing/export',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_billing_softDelete' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::softDeleteAction',    '_sonata_admin' => 'vault.admin.billing',    '_sonata_name' => 'admin_vault_billing_softDelete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/billing/softDelete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_meter_list' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::listAction',    '_sonata_admin' => 'vault.admin.meter',    '_sonata_name' => 'admin_vault_meter_list',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/meter/list',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_meter_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::createAction',    '_sonata_admin' => 'vault.admin.meter',    '_sonata_name' => 'admin_vault_meter_create',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/meter/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_meter_batch' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::batchAction',    '_sonata_admin' => 'vault.admin.meter',    '_sonata_name' => 'admin_vault_meter_batch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/meter/batch',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_meter_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::editAction',    '_sonata_admin' => 'vault.admin.meter',    '_sonata_name' => 'admin_vault_meter_edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/meter',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_meter_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::showAction',    '_sonata_admin' => 'vault.admin.meter',    '_sonata_name' => 'admin_vault_meter_show',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/meter',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_meter_export' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::exportAction',    '_sonata_admin' => 'vault.admin.meter',    '_sonata_name' => 'admin_vault_meter_export',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/meter/export',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_meter_softDelete' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::softDeleteAction',    '_sonata_admin' => 'vault.admin.meter',    '_sonata_name' => 'admin_vault_meter_softDelete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/meter/softDelete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_billingdetail_list' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::listAction',    '_sonata_admin' => 'vault.admin.billing_detail',    '_sonata_name' => 'admin_vault_billingdetail_list',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/billingdetail/list',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_billingdetail_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::createAction',    '_sonata_admin' => 'vault.admin.billing_detail',    '_sonata_name' => 'admin_vault_billingdetail_create',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/billingdetail/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_billingdetail_batch' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::batchAction',    '_sonata_admin' => 'vault.admin.billing_detail',    '_sonata_name' => 'admin_vault_billingdetail_batch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/billingdetail/batch',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_billingdetail_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::editAction',    '_sonata_admin' => 'vault.admin.billing_detail',    '_sonata_name' => 'admin_vault_billingdetail_edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/billingdetail',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_billingdetail_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::showAction',    '_sonata_admin' => 'vault.admin.billing_detail',    '_sonata_name' => 'admin_vault_billingdetail_show',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/billingdetail',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_billingdetail_export' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::exportAction',    '_sonata_admin' => 'vault.admin.billing_detail',    '_sonata_name' => 'admin_vault_billingdetail_export',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/billingdetail/export',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_billingdetail_softDelete' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::softDeleteAction',    '_sonata_admin' => 'vault.admin.billing_detail',    '_sonata_name' => 'admin_vault_billingdetail_softDelete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/billingdetail/softDelete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_consumption_list' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::listAction',    '_sonata_admin' => 'vault.admin.consumption',    '_sonata_name' => 'admin_vault_consumption_list',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/consumption/list',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_consumption_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::createAction',    '_sonata_admin' => 'vault.admin.consumption',    '_sonata_name' => 'admin_vault_consumption_create',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/consumption/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_consumption_batch' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::batchAction',    '_sonata_admin' => 'vault.admin.consumption',    '_sonata_name' => 'admin_vault_consumption_batch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/consumption/batch',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_consumption_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::editAction',    '_sonata_admin' => 'vault.admin.consumption',    '_sonata_name' => 'admin_vault_consumption_edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/consumption',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_consumption_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::showAction',    '_sonata_admin' => 'vault.admin.consumption',    '_sonata_name' => 'admin_vault_consumption_show',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/consumption',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_consumption_export' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::exportAction',    '_sonata_admin' => 'vault.admin.consumption',    '_sonata_name' => 'admin_vault_consumption_export',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/consumption/export',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_consumption_softDelete' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::softDeleteAction',    '_sonata_admin' => 'vault.admin.consumption',    '_sonata_name' => 'admin_vault_consumption_softDelete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/consumption/softDelete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_contractconsumption_list' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::listAction',    '_sonata_admin' => 'vault.admin.contract_consumption',    '_sonata_name' => 'admin_vault_contractconsumption_list',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/contractconsumption/list',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_contractconsumption_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::createAction',    '_sonata_admin' => 'vault.admin.contract_consumption',    '_sonata_name' => 'admin_vault_contractconsumption_create',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/contractconsumption/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_contractconsumption_batch' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::batchAction',    '_sonata_admin' => 'vault.admin.contract_consumption',    '_sonata_name' => 'admin_vault_contractconsumption_batch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/contractconsumption/batch',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_contractconsumption_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::editAction',    '_sonata_admin' => 'vault.admin.contract_consumption',    '_sonata_name' => 'admin_vault_contractconsumption_edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/contractconsumption',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_contractconsumption_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::showAction',    '_sonata_admin' => 'vault.admin.contract_consumption',    '_sonata_name' => 'admin_vault_contractconsumption_show',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/vault/contractconsumption',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_contractconsumption_export' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::exportAction',    '_sonata_admin' => 'vault.admin.contract_consumption',    '_sonata_name' => 'admin_vault_contractconsumption_export',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/contractconsumption/export',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_vault_contractconsumption_softDelete' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'VaultBundle\\Controller\\CRUDController::softDeleteAction',    '_sonata_admin' => 'vault.admin.contract_consumption',    '_sonata_name' => 'admin_vault_contractconsumption_softDelete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/vault/contractconsumption/softDelete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_sonata_user_user_list' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CRUDController::listAction',    '_sonata_admin' => 'sonata.user.admin.user',    '_sonata_name' => 'admin_sonata_user_user_list',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/sonata/user/user/list',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_sonata_user_user_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CRUDController::createAction',    '_sonata_admin' => 'sonata.user.admin.user',    '_sonata_name' => 'admin_sonata_user_user_create',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/sonata/user/user/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_sonata_user_user_batch' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CRUDController::batchAction',    '_sonata_admin' => 'sonata.user.admin.user',    '_sonata_name' => 'admin_sonata_user_user_batch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/sonata/user/user/batch',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_sonata_user_user_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CRUDController::editAction',    '_sonata_admin' => 'sonata.user.admin.user',    '_sonata_name' => 'admin_sonata_user_user_edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/sonata/user/user',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_sonata_user_user_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CRUDController::deleteAction',    '_sonata_admin' => 'sonata.user.admin.user',    '_sonata_name' => 'admin_sonata_user_user_delete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/sonata/user/user',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_sonata_user_user_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CRUDController::showAction',    '_sonata_admin' => 'sonata.user.admin.user',    '_sonata_name' => 'admin_sonata_user_user_show',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/sonata/user/user',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_sonata_user_user_export' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CRUDController::exportAction',    '_sonata_admin' => 'sonata.user.admin.user',    '_sonata_name' => 'admin_sonata_user_user_export',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/sonata/user/user/export',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_sonata_user_group_list' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CRUDController::listAction',    '_sonata_admin' => 'sonata.user.admin.group',    '_sonata_name' => 'admin_sonata_user_group_list',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/sonata/user/group/list',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_sonata_user_group_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CRUDController::createAction',    '_sonata_admin' => 'sonata.user.admin.group',    '_sonata_name' => 'admin_sonata_user_group_create',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/sonata/user/group/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_sonata_user_group_batch' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CRUDController::batchAction',    '_sonata_admin' => 'sonata.user.admin.group',    '_sonata_name' => 'admin_sonata_user_group_batch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/sonata/user/group/batch',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_sonata_user_group_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CRUDController::editAction',    '_sonata_admin' => 'sonata.user.admin.group',    '_sonata_name' => 'admin_sonata_user_group_edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/sonata/user/group',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_sonata_user_group_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CRUDController::deleteAction',    '_sonata_admin' => 'sonata.user.admin.group',    '_sonata_name' => 'admin_sonata_user_group_delete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/sonata/user/group',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_sonata_user_group_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CRUDController::showAction',    '_sonata_admin' => 'sonata.user.admin.group',    '_sonata_name' => 'admin_sonata_user_group_show',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/admin/sonata/user/group',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_sonata_user_group_export' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sonata\\AdminBundle\\Controller\\CRUDController::exportAction',    '_sonata_admin' => 'sonata.user.admin.group',    '_sonata_name' => 'admin_sonata_user_group_export',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/sonata/user/group/export',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
    );
        }
    }

    public function generate($name, $parameters = array(), $referenceType = self::ABSOLUTE_PATH)
    {
        if (!isset(self::$declaredRoutes[$name])) {
            throw new RouteNotFoundException(sprintf('Unable to generate a URL for the named route "%s" as such route does not exist.', $name));
        }

        list($variables, $defaults, $requirements, $tokens, $hostTokens, $requiredSchemes) = self::$declaredRoutes[$name];

        return $this->doGenerate($variables, $defaults, $requirements, $tokens, $parameters, $name, $referenceType, $hostTokens, $requiredSchemes);
    }
}
